### ISSUE TITLE
How could I insert picture?

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [tim-st/latex-cheatsheet#1]
I tried with following in one `section.tex` but the picture doesn't appear.
```
\begin{figure}
  \includegraphics[width=\linewidth]{example.png}
\end{figure}
```

Could you show a version with inserted picture?

**Comment by tim-st** [comment]
When you remove the figure environment it works. In the log it says multicols doesnt support floats and marginpars.

**Comment by cakebytheoceanLuo** [comment]
Thanks!
