### ISSUE TITLE
How to set the font globally?

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [tim-st/latex-cheatsheet#2]
For example I want to set the font all to `\tiny{text}`. Can could I do that?

**Comment by tim-st** [comment]
I don't know what you mean exactly. If you want to set the font size see
https://github.com/tim-st/latex-cheatsheet/blob/master/hilfszettel.tex#L24
and
https://github.com/tim-st/latex-cheatsheet/blob/master/hilfszettel.tex#L25

**Comment by cakebytheoceanLuo** [comment]
Danke!
