### ISSUE TITLE
Re-use the space of the name box

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [tim-st/latex-cheatsheet#3]
Hi Tim, 
As we know, the following things give us the `name box` at top of the left column.
But if I just comment thing block of code out, the `name box` will disapear, **but the blank space for the name box is still remaining**.
How can I re-use this blank space for my maximal cheatsheet?
Thanks!
```
\global\mdfdefinestyle{header}{%
linecolor=gray,linewidth=1pt,%
leftmargin=0mm,rightmargin=0mm,skipbelow=0mm,skipabove=0mm,
}

\newcommand{\header}{
\begin{mdframed}[style=header]
\footnotesize
\sffamily
Hilfszettel zur Klausur\\
von~Jigao,~Seite~\thepage~von~2
\end{mdframed}
}
```

**Comment by cakebytheoceanLuo** [comment]
What I mean in my cheatsheet:
![screenshot from 2019-02-11 22-26-47](https://user-images.githubusercontent.com/28505034/52594576-2682a880-2e4c-11e9-9d0b-0c711b4e29c3.png)
This happens at the top of the left column.
There is always a space left (was for `name box`, but I don't need it).
How can I re-use this space maximal?

**Comment by tim-st** [comment]
Do you want this name box removed all over the sheet or do you want to have it on page 1 but removed on all other pages?

**Comment by cakebytheoceanLuo** [comment]
Hi.
I want to remove all `name box` on all the pages.

**Comment by tim-st** [comment]
Remove these lines and it should produces the output you want:
https://github.com/tim-st/latex-cheatsheet/blob/master/inhalt/def.tex#L47-L157

**Comment by cakebytheoceanLuo** [comment]
Thanks
